# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Generate secret
          uses: 1password/load-secrets-action@v1
          run: op item template get Login | op item create --vault CICD --title='Demo' --generate-password='letters,digits,symbols,32' -
          
#       - name: Load secret
#         uses: 1password/load-secrets-action@v1
#         env:
#           SECRET: op://app-cicd/hello-world/secret
